import type { DashboardSnapshot } from "@/lib/operations-types";

export const mockOperationsSnapshot: DashboardSnapshot = {
  productName: "Moto Ops Control",
  generatedAt: "2026-03-29T16:20:00Z",
  highlightedTicketId: "tkt_0041",
  viewer: {
    role: "admin",
    name: "Admin Console",
    permissions: [
      "ticket.view",
      "ticket.message",
      "ticket.close",
      "inventory.view",
      "inventory.edit",
    ],
  },
  roleMatrix: [
    {
      role: "admin",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.close",
        "inventory.view",
        "inventory.edit",
      ],
      closeTickets: true,
      editInventory: true,
      canChat: true,
    },
    {
      role: "logistics",
      permissions: ["ticket.view", "ticket.message", "ticket.close"],
      closeTickets: true,
      editInventory: false,
      canChat: true,
    },
    {
      role: "factory_operator",
      permissions: ["ticket.view", "ticket.message"],
      closeTickets: false,
      editInventory: false,
      canChat: true,
    },
    {
      role: "ingestion",
      permissions: ["ticket.view", "ticket.message"],
      closeTickets: false,
      editInventory: false,
      canChat: true,
    },
  ],
  metrics: [
    {
      label: "Tickets In Motion",
      value: "18",
      helper: "Accepted, shipped, and ingestion-stage requests",
      tone: "info",
    },
    {
      label: "Returns Waiting At HQ",
      value: "06",
      helper: "Packets ready for handoff or reconciliation",
      tone: "warning",
    },
    {
      label: "Ingestion Queue",
      value: "14",
      helper: "Packets currently visible inside the ingestion room",
      tone: "neutral",
    },
    {
      label: "Missing SD Cards",
      value: "32",
      helper: "Detected this week across HQ receipt and ingestion",
      tone: "error",
    },
    {
      label: "Clean Closures",
      value: "91%",
      helper: "Tickets closed with zero discrepancy this month",
      tone: "success",
    },
  ],
  tickets: [
    {
      id: "tkt_0041",
      title:
        "Tata Team A | Pune Factory 2 | Deploy 2026-04-02 | Devices 500 | SD Cards 500",
      teamName: "Tata Team A",
      factoryName: "Pune Factory 2",
      deploymentDate: "2026-04-02",
      workerCount: 500,
      status: "ingestion_processing",
      priority: "high",
      devicesRequested: 500,
      sdCardsRequested: 500,
      requestOwner: "Raghu M",
      summary:
        "Full factory deployment pack has returned to HQ. Ingestion has started and card mismatch is being tracked.",
      nextAction: "Ingestion team must finalize working, missing, and faulty card counts.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 500,
          receivedAtHqQty: 500,
        },
        {
          itemType: "Chargers",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 497,
          receivedAtHqQty: 497,
        },
        {
          itemType: "SD cards",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 462,
          receivedAtHqQty: 450,
        },
        {
          itemType: "Reader hubs",
          requestedQty: 12,
          approvedQty: 12,
          returnedQty: 12,
          receivedAtHqQty: 12,
        },
      ],
      packages: [
        {
          packageCode: "PKG-RET-041A",
          qrToken: "qr_041a",
          direction: "return",
          status: "hq_received",
          itemCount: 3,
          note: "Blue pouch returned through HQ dock 2",
        },
        {
          packageCode: "PKG-RET-041B",
          qrToken: "qr_041b",
          direction: "return",
          status: "transferred_to_ingestion",
          itemCount: 1,
          note: "SD card pouch handed to station J-03",
        },
      ],
      messages: [
        {
          id: "msg_01",
          author: "Raghu M",
          role: "operator",
          sentAt: "2026-03-29T09:00:00Z",
          message:
            "Need full deployment pack for 500 workers. Deployment starts on April 2.",
        },
        {
          id: "msg_02",
          author: "Sonal P",
          role: "logistics",
          sentAt: "2026-03-29T11:10:00Z",
          message:
            "Accepted. We are packing devices, chargers, SD cards, and reader hubs in two packets.",
        },
        {
          id: "msg_03",
          author: "Sonal P",
          role: "logistics",
          sentAt: "2026-04-13T18:30:00Z",
          message:
            "Return packet received at HQ. SD card pouch is being transferred to ingestion now.",
        },
        {
          id: "msg_04",
          author: "Harish K",
          role: "ingestion",
          sentAt: "2026-04-14T11:05:00Z",
          message:
            "Ingestion processing started on station J-03. Preliminary count is below expected.",
        },
      ],
      timeline: [
        {
          id: "evt_01",
          label: "Ticket opened",
          detail: "Factory team created the request with the full hardware list.",
          occurredAt: "2026-03-29T09:00:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_02",
          label: "Ticket accepted",
          detail: "Logistics confirmed stock and approved the complete request.",
          occurredAt: "2026-03-29T11:05:00Z",
          actor: "Sonal P",
          tone: "success",
        },
        {
          id: "evt_03",
          label: "Outbound shipped",
          detail: "Two packets dispatched with QR labels and item counts.",
          occurredAt: "2026-03-31T16:20:00Z",
          actor: "HQ Logistics",
          tone: "info",
        },
        {
          id: "evt_04",
          label: "Received at factory",
          detail: "Operator confirmed arrival and noted no major outbound mismatch.",
          occurredAt: "2026-04-02T08:40:00Z",
          actor: "Raghu M",
          tone: "success",
        },
        {
          id: "evt_05",
          label: "Return shipped",
          detail: "Deployment completed. Return pouch sent back to headquarters.",
          occurredAt: "2026-04-12T17:35:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_06",
          label: "Received at HQ",
          detail: "Counts recorded at dock 2. SD cards below expected return quantity.",
          occurredAt: "2026-04-13T18:15:00Z",
          actor: "Sonal P",
          tone: "warning",
        },
        {
          id: "evt_07",
          label: "Transferred to ingestion",
          detail: "SD card pouch moved to room J with QR-linked packet identity.",
          occurredAt: "2026-04-14T10:20:00Z",
          actor: "Sonal P",
          tone: "info",
        },
        {
          id: "evt_08",
          label: "Ingestion processing",
          detail: "Station J-03 is counting and ingesting returned SD card data.",
          occurredAt: "2026-04-14T11:00:00Z",
          actor: "Harish K",
          tone: "warning",
        },
      ],
      ingestionReport: {
        station: "J-03",
        startedAt: "2026-04-14T11:00:00Z",
        expectedSdCards: 500,
        actualSdCardsReceived: 450,
        processedSdCards: 438,
        missingSdCards: 50,
        faultySdCards: 12,
        note: "Red-marked cards separated for manual review before closure.",
      },
    },
    {
      id: "tkt_0042",
      title:
        "Ashok Team C | Hosur Plant 1 | Deploy 2026-04-04 | Devices 220 | SD Cards 220",
      teamName: "Ashok Team C",
      factoryName: "Hosur Plant 1",
      deploymentDate: "2026-04-04",
      workerCount: 220,
      status: "accepted",
      priority: "medium",
      devicesRequested: 220,
      sdCardsRequested: 220,
      requestOwner: "Priya S",
      summary: "Accepted and waiting for outbound packaging.",
      nextAction: "Logistics must generate QR packet labels and dispatch the shipment.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 220,
          approvedQty: 220,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
        {
          itemType: "SD cards",
          requestedQty: 220,
          approvedQty: 220,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
      ],
      packages: [
        {
          packageCode: "PKG-OUT-042A",
          qrToken: "qr_042a",
          direction: "outbound",
          status: "accepted",
          itemCount: 2,
          note: "Packing lane reserved for tomorrow morning",
        },
      ],
      messages: [
        {
          id: "msg_05",
          author: "Priya S",
          role: "operator",
          sentAt: "2026-03-29T10:15:00Z",
          message: "Please prioritize. Deployment starts early morning on April 4.",
        },
        {
          id: "msg_06",
          author: "Vikas R",
          role: "logistics",
          sentAt: "2026-03-29T12:05:00Z",
          message: "Accepted. QR labels will be created during the evening dispatch cycle.",
        },
      ],
      timeline: [
        {
          id: "evt_09",
          label: "Ticket opened",
          detail: "Operator requested 220 devices and 220 SD cards.",
          occurredAt: "2026-03-29T10:15:00Z",
          actor: "Priya S",
          tone: "info",
        },
        {
          id: "evt_10",
          label: "Ticket accepted",
          detail: "Logistics approved full quantity and scheduled pack-out.",
          occurredAt: "2026-03-29T12:00:00Z",
          actor: "Vikas R",
          tone: "success",
        },
      ],
      ingestionReport: null,
    },
    {
      id: "tkt_0043",
      title:
        "TVS Team B | Chennai Assembly | Deploy 2026-04-05 | Devices 180 | SD Cards 200",
      teamName: "TVS Team B",
      factoryName: "Chennai Assembly",
      deploymentDate: "2026-04-05",
      workerCount: 180,
      status: "return_shipped",
      priority: "high",
      devicesRequested: 180,
      sdCardsRequested: 200,
      requestOwner: "Anbu K",
      summary: "Return packet is in transit back to HQ after field completion.",
      nextAction: "HQ logistics must receive the return and record actual counts.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 180,
          approvedQty: 180,
          returnedQty: 180,
          receivedAtHqQty: 0,
        },
        {
          itemType: "SD cards",
          requestedQty: 200,
          approvedQty: 200,
          returnedQty: 193,
          receivedAtHqQty: 0,
        },
      ],
      packages: [
        {
          packageCode: "PKG-RET-043A",
          qrToken: "qr_043a",
          direction: "return",
          status: "return_shipped",
          itemCount: 2,
          note: "Courier handoff completed with manifest attached",
        },
      ],
      messages: [
        {
          id: "msg_07",
          author: "Anbu K",
          role: "operator",
          sentAt: "2026-04-11T18:20:00Z",
          message: "Return packet shipped. Tracking number shared in manifest.",
        },
      ],
      timeline: [
        {
          id: "evt_11",
          label: "Outbound shipped",
          detail: "Dispatch closed with one mixed hardware packet and one SD pouch.",
          occurredAt: "2026-04-03T15:45:00Z",
          actor: "HQ Logistics",
          tone: "info",
        },
        {
          id: "evt_12",
          label: "Return shipped",
          detail: "Factory team shipped back the packet after deployment finished.",
          occurredAt: "2026-04-11T18:20:00Z",
          actor: "Anbu K",
          tone: "warning",
        },
      ],
      ingestionReport: null,
    },
  ],
  ingestionQueue: [
    {
      id: "ing_041",
      packageCode: "PKG-RET-041B",
      teamName: "Tata Team A",
      factoryName: "Pune Factory 2",
      deploymentDate: "2026-04-02",
      expectedSdCards: 500,
      status: "ingestion_processing",
    },
    {
      id: "ing_036",
      packageCode: "PKG-RET-036A",
      teamName: "Hindalco Team D",
      factoryName: "Nagpur Press Line",
      deploymentDate: "2026-03-31",
      expectedSdCards: 160,
      status: "transferred_to_ingestion",
    },
    {
      id: "ing_032",
      packageCode: "PKG-RET-032C",
      teamName: "Mahindra Team F",
      factoryName: "Nashik Body Shop",
      deploymentDate: "2026-03-28",
      expectedSdCards: 90,
      status: "hq_received",
    },
  ],
  inventoryItems: [
    {
      id: "inv_camera",
      itemType: "Camera devices",
      sku: "CAM-HEAD-01",
      totalUnits: 1500,
      availableUnits: 612,
      allocatedUnits: 540,
      inTransitUnits: 198,
      ingestionUnits: 0,
      missingUnits: 150,
      reorderPoint: 400,
      location: "HQ Rack A1",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T17:05:00Z",
      note: "Admin reconciled counts after return scan batch.",
      status: "critical",
    },
    {
      id: "inv_sd_cards",
      itemType: "SD cards",
      sku: "SD-256-IND",
      totalUnits: 2800,
      availableUnits: 720,
      allocatedUnits: 910,
      inTransitUnits: 610,
      ingestionUnits: 528,
      missingUnits: 32,
      reorderPoint: 850,
      location: "Vault C2",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T17:08:00Z",
      note: "Missing cards reflect latest ingestion discrepancy count.",
      status: "low_stock",
    },
    {
      id: "inv_chargers",
      itemType: "Chargers",
      sku: "CHR-65W-IND",
      totalUnits: 1700,
      availableUnits: 884,
      allocatedUnits: 520,
      inTransitUnits: 210,
      ingestionUnits: 0,
      missingUnits: 86,
      reorderPoint: 300,
      location: "HQ Rack B3",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T16:42:00Z",
      note: "Includes shortage from two incomplete factory returns.",
      status: "critical",
    },
    {
      id: "inv_reader_hubs",
      itemType: "Reader hubs",
      sku: "HUB-12X-IND",
      totalUnits: 120,
      availableUnits: 54,
      allocatedUnits: 28,
      inTransitUnits: 18,
      ingestionUnits: 12,
      missingUnits: 8,
      reorderPoint: 20,
      location: "Lab Shelf D1",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T16:55:00Z",
      note: "Extra units reserved for ingestion room overflow.",
      status: "low_stock",
    },
  ],
};

export function getMockOperationsSnapshot() {
  return mockOperationsSnapshot;
}
