import type { DashboardSnapshot } from "@/lib/operations-types";

export const mockOperationsSnapshot: DashboardSnapshot = {
  productName: "Build AI",
  generatedAt: "2026-03-29T16:20:00Z",
  highlightedTicketId: "tkt_0041",
  viewer: {
    role: "admin",
    name: "Admin Console",
    permissions: [
      "ticket.view",
      "ticket.message",
      "ticket.close",
      "ticket.create",
      "ticket.status.update",
      "package.view",
      "package.edit",
      "package.status.update",
      "ingestion.reconcile",
      "inventory.view",
      "inventory.edit",
      "user.manage",
    ],
  },
  roleMatrix: [
    {
      role: "admin",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.close",
        "ticket.create",
        "ticket.status.update",
        "package.view",
        "package.edit",
        "package.status.update",
        "ingestion.reconcile",
        "inventory.view",
        "inventory.edit",
        "user.manage",
      ],
      closeTickets: true,
      editInventory: true,
      canChat: true,
      canCreateTickets: true,
      canUpdateStatus: true,
    },
    {
      role: "logistics",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.close",
        "ticket.status.update",
        "package.view",
        "package.edit",
        "package.status.update",
      ],
      closeTickets: true,
      editInventory: false,
      canChat: true,
      canCreateTickets: false,
      canUpdateStatus: true,
    },
    {
      role: "factory_operator",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.create",
        "ticket.status.update",
        "package.view",
        "package.edit",
        "package.status.update",
      ],
      closeTickets: false,
      editInventory: false,
      canChat: true,
      canCreateTickets: true,
      canUpdateStatus: true,
    },
    {
      role: "ingestion",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.close",
        "ticket.status.update",
        "package.view",
        "package.status.update",
        "ingestion.reconcile",
      ],
      closeTickets: true,
      editInventory: false,
      canChat: true,
      canCreateTickets: false,
      canUpdateStatus: true,
    },
  ],
  metrics: [
    {
      label: "Tickets In Motion",
      value: "01",
      helper: "Single seeded deployment request in active flow",
      tone: "info",
    },
    {
      label: "Returns Waiting At HQ",
      value: "00",
      helper: "No additional seeded packets are waiting at headquarters",
      tone: "warning",
    },
    {
      label: "Ingestion Queue",
      value: "01",
      helper: "One seeded packet is visible inside the ingestion room",
      tone: "neutral",
    },
    {
      label: "Missing SD Cards",
      value: "50",
      helper: "Single seeded discrepancy from the return packet",
      tone: "error",
    },
    {
      label: "Clean Closures",
      value: "00%",
      helper: "No seeded ticket has been closed yet",
      tone: "success",
    },
  ],
  meritScores: [
    {
      teamName: "Tata Team A",
      score: 94.65,
      sdCardPenalty: 5,
      devicePenalty: 0,
      accessoryPenalty: 0.35,
      sdCardShortfall: 50,
      deviceShortfall: 0,
      accessoryShortfall: 3,
      updatedAt: "2026-04-14T11:00:00Z",
    },
  ],
  movementHistory: [
    {
      id: "mv_tkt_0041",
      ticketId: "tkt_0041",
      ticketType: "deployment",
      status: "ingestion_processing",
      sourceLabel: "HQ Logistics",
      destinationLabel: "Tata Team A / Pune Factory 2",
      routePath: ["HQ", "Pune Factory 2"],
      routeSummary: "HQ -> Pune Factory 2",
      relatedTicketId: null,
      devicesCount: 500,
      sdCardsCount: 500,
      usbHubsCount: 0,
      cablesCount: 0,
      packageCount: 1,
      lastEventAt: "2026-04-14T11:00:00Z",
      note:
        "Full factory deployment pack returned to HQ. Ingestion has started and the SD card mismatch is being tracked.",
    },
  ],
  tickets: [
    {
      id: "tkt_0041",
      title:
        "Tata Team A | Pune Factory 2 | Deploy 2026-04-02 | Devices 500 | SD Cards 500",
      ticketType: "deployment",
      teamName: "Tata Team A",
      factoryName: "Pune Factory 2",
      deploymentDate: "2026-04-02",
      workerCount: 500,
      status: "ingestion_processing",
      priority: "high",
      devicesRequested: 500,
      sdCardsRequested: 500,
      requestOwner: "Raghu M",
      summary:
        "Full factory deployment pack returned to HQ. Ingestion has started and the SD card mismatch is being tracked.",
      nextAction: "Ingestion team must finalize working, missing, and faulty card counts.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 500,
          receivedAtHqQty: 500,
        },
        {
          itemType: "Chargers",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 497,
          receivedAtHqQty: 497,
        },
        {
          itemType: "SD cards",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 462,
          receivedAtHqQty: 450,
        },
        {
          itemType: "Reader hubs",
          requestedQty: 12,
          approvedQty: 12,
          returnedQty: 12,
          receivedAtHqQty: 12,
        },
      ],
      packages: [
        {
          packageCode: "PKG-RET-041A",
          qrToken: "qr_041a",
          direction: "return",
          status: "ingestion_processing",
          itemCount: 1,
          shippedSdCardsCount: 500,
          shippedDevicesCount: 0,
          shippedUsbHubsCount: 0,
          shippedCablesCount: 0,
          receivedSdCardsCount: 450,
          receivedDevicesCount: 0,
          receivedUsbHubsCount: 0,
          receivedCablesCount: 0,
          note: "Single seeded return pouch moved into ingestion",
          teamName: "Tata Team A",
          factoryName: "Pune Factory 2",
          deploymentDate: "2026-04-02",
          updatedAt: "2026-04-14T10:20:00Z",
          updatedBy: "Sonal P",
        },
      ],
      messages: [
        {
          id: "msg_01",
          author: "Raghu M",
          role: "operator",
          sentAt: "2026-03-29T09:00:00Z",
          message:
            "Need full deployment pack for 500 workers. Deployment starts on April 2.",
        },
        {
          id: "msg_02",
          author: "Sonal P",
          role: "logistics",
          sentAt: "2026-03-29T11:10:00Z",
          message:
            "Accepted. We are packing devices, chargers, SD cards, and reader hubs in one tracked packet.",
        },
        {
          id: "msg_03",
          author: "Harish K",
          role: "ingestion",
          sentAt: "2026-04-14T11:05:00Z",
          message:
            "Ingestion processing started on station J-03. Preliminary count is below expected.",
        },
      ],
      timeline: [
        {
          id: "evt_01",
          label: "Ticket opened",
          detail: "Factory team created the request with the full hardware list.",
          occurredAt: "2026-03-29T09:00:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_02",
          label: "Ticket accepted",
          detail: "Logistics confirmed stock and approved the complete request.",
          occurredAt: "2026-03-29T11:05:00Z",
          actor: "Sonal P",
          tone: "success",
        },
        {
          id: "evt_03",
          label: "Outbound shipped",
          detail: "Single tracked packet dispatched with QR label and item counts.",
          occurredAt: "2026-03-31T16:20:00Z",
          actor: "HQ Logistics",
          tone: "info",
        },
        {
          id: "evt_04",
          label: "Received at factory",
          detail: "Operator confirmed arrival and noted no major outbound mismatch.",
          occurredAt: "2026-04-02T08:40:00Z",
          actor: "Raghu M",
          tone: "success",
        },
        {
          id: "evt_05",
          label: "Return shipped",
          detail: "Deployment completed. Return pouch sent back to headquarters.",
          occurredAt: "2026-04-12T17:35:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_06",
          label: "Received at HQ",
          detail: "Counts recorded at dock 2. SD cards below expected return quantity.",
          occurredAt: "2026-04-13T18:15:00Z",
          actor: "Sonal P",
          tone: "warning",
        },
        {
          id: "evt_07",
          label: "Ingestion processing",
          detail: "Station J-03 is counting and ingesting returned SD card data.",
          occurredAt: "2026-04-14T11:00:00Z",
          actor: "Harish K",
          tone: "warning",
        },
      ],
      ingestionReport: {
        station: "J-03",
        startedAt: "2026-04-14T11:00:00Z",
        expectedSdCards: 500,
        actualSdCardsReceived: 450,
        processedSdCards: 438,
        missingSdCards: 50,
        faultySdCards: 12,
        note: "Red-marked cards separated for manual review before closure.",
      },
      members: [],
    },
  ],
  ingestionQueue: [
    {
      id: "ing_041",
      packageCode: "PKG-RET-041A",
      teamName: "Tata Team A",
      factoryName: "Pune Factory 2",
      deploymentDate: "2026-04-02",
      expectedSdCards: 450,
      status: "ingestion_processing",
    },
  ],
  inventoryItems: [
    {
      id: "inv_camera",
      itemType: "Camera devices",
      sku: "CAM-HEAD-01",
      totalUnits: 1500,
      availableUnits: 612,
      allocatedUnits: 540,
      inTransitUnits: 198,
      ingestionUnits: 0,
      missingUnits: 150,
      reorderPoint: 400,
      location: "HQ Rack A1",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T17:05:00Z",
      note: "Admin reconciled counts after return scan batch.",
      status: "critical",
    },
    {
      id: "inv_sd_cards",
      itemType: "SD cards",
      sku: "SD-256-IND",
      totalUnits: 2800,
      availableUnits: 720,
      allocatedUnits: 910,
      inTransitUnits: 610,
      ingestionUnits: 528,
      missingUnits: 50,
      reorderPoint: 850,
      location: "Vault C2",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T17:08:00Z",
      note: "Missing cards reflect the single seeded ingestion discrepancy.",
      status: "low_stock",
    },
    {
      id: "inv_chargers",
      itemType: "Chargers",
      sku: "CHR-65W-IND",
      totalUnits: 1700,
      availableUnits: 884,
      allocatedUnits: 520,
      inTransitUnits: 210,
      ingestionUnits: 0,
      missingUnits: 86,
      reorderPoint: 300,
      location: "HQ Rack B3",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T16:42:00Z",
      note: "Includes shortage from incomplete return reconciliation.",
      status: "critical",
    },
    {
      id: "inv_reader_hubs",
      itemType: "Reader hubs",
      sku: "HUB-12X-IND",
      totalUnits: 120,
      availableUnits: 54,
      allocatedUnits: 28,
      inTransitUnits: 18,
      ingestionUnits: 12,
      missingUnits: 8,
      reorderPoint: 20,
      location: "Lab Shelf D1",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T16:55:00Z",
      note: "Extra units reserved for ingestion room overflow.",
      status: "low_stock",
    },
  ],
};

export function getMockOperationsSnapshot() {
  return mockOperationsSnapshot;
}
