import type { DashboardSnapshot } from "@/lib/operations-types";

export const mockOperationsSnapshot: DashboardSnapshot = {
  productName: "Build AI",
  generatedAt: "2026-03-29T16:20:00Z",
  highlightedTicketId: "tkt_0041",
  viewer: {
    role: "admin",
    name: "Admin Console",
    permissions: [
      "ticket.view",
      "ticket.message",
      "ticket.close",
      "ticket.create",
      "ticket.status.update",
      "package.view",
      "package.edit",
      "package.status.update",
      "ingestion.reconcile",
      "inventory.view",
      "inventory.edit",
      "user.manage",
    ],
  },
  roleMatrix: [
    {
      role: "admin",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.close",
        "ticket.create",
        "ticket.status.update",
        "package.view",
        "package.edit",
        "package.status.update",
        "ingestion.reconcile",
        "inventory.view",
        "inventory.edit",
        "user.manage",
      ],
      closeTickets: true,
      editInventory: true,
      canChat: true,
      canCreateTickets: true,
      canUpdateStatus: true,
    },
    {
      role: "logistics",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.close",
        "ticket.status.update",
        "package.view",
        "package.edit",
        "package.status.update",
      ],
      closeTickets: true,
      editInventory: false,
      canChat: true,
      canCreateTickets: false,
      canUpdateStatus: true,
    },
    {
      role: "factory_operator",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.create",
        "ticket.status.update",
        "package.view",
        "package.edit",
        "package.status.update",
      ],
      closeTickets: false,
      editInventory: false,
      canChat: true,
      canCreateTickets: true,
      canUpdateStatus: true,
    },
    {
      role: "ingestion",
      permissions: [
        "ticket.view",
        "ticket.message",
        "ticket.status.update",
        "package.view",
        "package.status.update",
        "ingestion.reconcile",
      ],
      closeTickets: false,
      editInventory: false,
      canChat: true,
      canCreateTickets: false,
      canUpdateStatus: true,
    },
  ],
  metrics: [
    {
      label: "Tickets In Motion",
      value: "18",
      helper: "Accepted, shipped, and ingestion-stage requests",
      tone: "info",
    },
    {
      label: "Returns Waiting At HQ",
      value: "06",
      helper: "Packets ready for handoff or reconciliation",
      tone: "warning",
    },
    {
      label: "Ingestion Queue",
      value: "14",
      helper: "Packets currently visible inside the ingestion room",
      tone: "neutral",
    },
    {
      label: "Missing SD Cards",
      value: "32",
      helper: "Detected this week across HQ receipt and ingestion",
      tone: "error",
    },
    {
      label: "Clean Closures",
      value: "91%",
      helper: "Tickets closed with zero discrepancy this month",
      tone: "success",
    },
  ],
  meritScores: [
    {
      teamName: "Tata Team A",
      score: 94.65,
      sdCardPenalty: 5,
      devicePenalty: 0,
      accessoryPenalty: 0.35,
      sdCardShortfall: 50,
      deviceShortfall: 0,
      accessoryShortfall: 3,
      updatedAt: "2026-04-14T11:00:00Z",
    },
    {
      teamName: "TVS Team B",
      score: 98.25,
      sdCardPenalty: 1.75,
      devicePenalty: 0,
      accessoryPenalty: 0,
      sdCardShortfall: 7,
      deviceShortfall: 0,
      accessoryShortfall: 0,
      updatedAt: "2026-04-11T18:20:00Z",
    },
  ],
  movementHistory: [
    {
      id: "mv_tkt_0044",
      ticketId: "tkt_0044",
      ticketType: "transfer",
      status: "factory_received",
      sourceLabel: "Tata Team A / Pune Factory 2",
      destinationLabel: "Ashok Team C / Hosur Plant 1",
      routePath: ["HQ", "Pune Factory 2", "Hosur Plant 1"],
      routeSummary: "HQ -> Pune Factory 2 -> Hosur Plant 1",
      relatedTicketId: "tkt_0041",
      devicesCount: 120,
      sdCardsCount: 0,
      usbHubsCount: 3,
      cablesCount: 120,
      packageCount: 1,
      lastEventAt: "2026-04-16T09:40:00Z",
      note: "Factory-to-factory transfer completed. Devices moved from Pune Factory 2 to Hosur Plant 1.",
    },
    {
      id: "mv_tkt_0041",
      ticketId: "tkt_0041",
      ticketType: "deployment",
      status: "ingestion_processing",
      sourceLabel: "HQ Logistics",
      destinationLabel: "Tata Team A / Pune Factory 2",
      routePath: ["HQ", "Pune Factory 2"],
      routeSummary: "HQ -> Pune Factory 2",
      devicesCount: 500,
      sdCardsCount: 500,
      usbHubsCount: 0,
      cablesCount: 0,
      packageCount: 2,
      lastEventAt: "2026-04-14T11:00:00Z",
      note: "Full factory deployment pack has returned to HQ. Ingestion has started and card mismatch is being tracked.",
    },
    {
      id: "mv_tkt_0043",
      ticketId: "tkt_0043",
      ticketType: "deployment",
      status: "return_shipped",
      sourceLabel: "HQ Logistics",
      destinationLabel: "TVS Team B / Chennai Assembly",
      routePath: ["HQ", "Chennai Assembly"],
      routeSummary: "HQ -> Chennai Assembly",
      devicesCount: 180,
      sdCardsCount: 200,
      usbHubsCount: 0,
      cablesCount: 0,
      packageCount: 1,
      lastEventAt: "2026-04-11T18:20:00Z",
      note: "Return packet is in transit back to HQ after field completion.",
    },
    {
      id: "mv_tkt_0042",
      ticketId: "tkt_0042",
      ticketType: "deployment",
      status: "accepted",
      sourceLabel: "HQ Logistics",
      destinationLabel: "Ashok Team C / Hosur Plant 1",
      routePath: ["HQ", "Hosur Plant 1"],
      routeSummary: "HQ -> Hosur Plant 1",
      devicesCount: 220,
      sdCardsCount: 220,
      usbHubsCount: 6,
      cablesCount: 220,
      packageCount: 1,
      lastEventAt: "2026-03-29T12:00:00Z",
      note: "Accepted and waiting for outbound packaging.",
    },
  ],
  tickets: [
    {
      id: "tkt_0041",
      title:
        "Tata Team A | Pune Factory 2 | Deploy 2026-04-02 | Devices 500 | SD Cards 500",
      ticketType: "deployment",
      teamName: "Tata Team A",
      factoryName: "Pune Factory 2",
      deploymentDate: "2026-04-02",
      workerCount: 500,
      status: "ingestion_processing",
      priority: "high",
      devicesRequested: 500,
      sdCardsRequested: 500,
      requestOwner: "Raghu M",
      summary:
        "Full factory deployment pack has returned to HQ. Ingestion has started and card mismatch is being tracked.",
      nextAction: "Ingestion team must finalize working, missing, and faulty card counts.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 500,
          receivedAtHqQty: 500,
        },
        {
          itemType: "Chargers",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 497,
          receivedAtHqQty: 497,
        },
        {
          itemType: "SD cards",
          requestedQty: 500,
          approvedQty: 500,
          returnedQty: 462,
          receivedAtHqQty: 450,
        },
        {
          itemType: "Reader hubs",
          requestedQty: 12,
          approvedQty: 12,
          returnedQty: 12,
          receivedAtHqQty: 12,
        },
      ],
      packages: [
        {
          packageCode: "PKG-RET-041A",
          qrToken: "qr_041a",
          direction: "return",
          status: "hq_received",
          itemCount: 3,
          shippedSdCardsCount: 250,
          shippedDevicesCount: 0,
          shippedUsbHubsCount: 0,
          shippedCablesCount: 0,
          receivedSdCardsCount: 248,
          receivedDevicesCount: 0,
          receivedUsbHubsCount: 0,
          receivedCablesCount: 0,
          note: "Blue pouch returned through HQ dock 2",
          teamName: "Tata Team A",
          factoryName: "Pune Factory 2",
          deploymentDate: "2026-04-02",
          updatedAt: "2026-04-13T18:15:00Z",
          updatedBy: "Sonal P",
        },
        {
          packageCode: "PKG-RET-041B",
          qrToken: "qr_041b",
          direction: "return",
          status: "transferred_to_ingestion",
          itemCount: 1,
          shippedSdCardsCount: 250,
          shippedDevicesCount: 0,
          shippedUsbHubsCount: 0,
          shippedCablesCount: 0,
          receivedSdCardsCount: 202,
          receivedDevicesCount: 0,
          receivedUsbHubsCount: 0,
          receivedCablesCount: 0,
          note: "SD card pouch handed to station J-03",
          teamName: "Tata Team A",
          factoryName: "Pune Factory 2",
          deploymentDate: "2026-04-03",
          updatedAt: "2026-04-14T10:20:00Z",
          updatedBy: "Sonal P",
        },
      ],
      messages: [
        {
          id: "msg_01",
          author: "Raghu M",
          role: "operator",
          sentAt: "2026-03-29T09:00:00Z",
          message:
            "Need full deployment pack for 500 workers. Deployment starts on April 2.",
        },
        {
          id: "msg_02",
          author: "Sonal P",
          role: "logistics",
          sentAt: "2026-03-29T11:10:00Z",
          message:
            "Accepted. We are packing devices, chargers, SD cards, and reader hubs in two packets.",
        },
        {
          id: "msg_03",
          author: "Sonal P",
          role: "logistics",
          sentAt: "2026-04-13T18:30:00Z",
          message:
            "Return packet received at HQ. SD card pouch is being transferred to ingestion now.",
        },
        {
          id: "msg_04",
          author: "Harish K",
          role: "ingestion",
          sentAt: "2026-04-14T11:05:00Z",
          message:
            "Ingestion processing started on station J-03. Preliminary count is below expected.",
        },
      ],
      timeline: [
        {
          id: "evt_01",
          label: "Ticket opened",
          detail: "Factory team created the request with the full hardware list.",
          occurredAt: "2026-03-29T09:00:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_02",
          label: "Ticket accepted",
          detail: "Logistics confirmed stock and approved the complete request.",
          occurredAt: "2026-03-29T11:05:00Z",
          actor: "Sonal P",
          tone: "success",
        },
        {
          id: "evt_03",
          label: "Outbound shipped",
          detail: "Two packets dispatched with QR labels and item counts.",
          occurredAt: "2026-03-31T16:20:00Z",
          actor: "HQ Logistics",
          tone: "info",
        },
        {
          id: "evt_04",
          label: "Received at factory",
          detail: "Operator confirmed arrival and noted no major outbound mismatch.",
          occurredAt: "2026-04-02T08:40:00Z",
          actor: "Raghu M",
          tone: "success",
        },
        {
          id: "evt_05",
          label: "Return shipped",
          detail: "Deployment completed. Return pouch sent back to headquarters.",
          occurredAt: "2026-04-12T17:35:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_06",
          label: "Received at HQ",
          detail: "Counts recorded at dock 2. SD cards below expected return quantity.",
          occurredAt: "2026-04-13T18:15:00Z",
          actor: "Sonal P",
          tone: "warning",
        },
        {
          id: "evt_07",
          label: "Transferred to ingestion",
          detail: "SD card pouch moved to room J with QR-linked packet identity.",
          occurredAt: "2026-04-14T10:20:00Z",
          actor: "Sonal P",
          tone: "info",
        },
        {
          id: "evt_08",
          label: "Ingestion processing",
          detail: "Station J-03 is counting and ingesting returned SD card data.",
          occurredAt: "2026-04-14T11:00:00Z",
          actor: "Harish K",
          tone: "warning",
        },
      ],
      ingestionReport: {
        station: "J-03",
        startedAt: "2026-04-14T11:00:00Z",
        expectedSdCards: 500,
        actualSdCardsReceived: 450,
        processedSdCards: 438,
        missingSdCards: 50,
        faultySdCards: 12,
        note: "Red-marked cards separated for manual review before closure.",
      },
    },
    {
      id: "tkt_0042",
      title:
        "Ashok Team C | Hosur Plant 1 | Deploy 2026-04-04 | Devices 220 | SD Cards 220",
      ticketType: "deployment",
      teamName: "Ashok Team C",
      factoryName: "Hosur Plant 1",
      deploymentDate: "2026-04-04",
      workerCount: 220,
      status: "accepted",
      priority: "medium",
      devicesRequested: 220,
      sdCardsRequested: 220,
      requestOwner: "Priya S",
      summary: "Accepted and waiting for outbound packaging.",
      nextAction: "Logistics must generate QR packet labels and dispatch the shipment.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 220,
          approvedQty: 220,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
        {
          itemType: "SD cards",
          requestedQty: 220,
          approvedQty: 220,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
      ],
      packages: [
        {
          packageCode: "PKG-OUT-042A",
          qrToken: "qr_042a",
          direction: "outbound",
          status: "accepted",
          itemCount: 2,
          shippedSdCardsCount: 220,
          shippedDevicesCount: 220,
          shippedUsbHubsCount: 6,
          shippedCablesCount: 220,
          receivedSdCardsCount: null,
          receivedDevicesCount: null,
          receivedUsbHubsCount: null,
          receivedCablesCount: null,
          note: "Packing lane reserved for tomorrow morning",
          teamName: "Ashok Team C",
          factoryName: "Hosur Plant 1",
          deploymentDate: null,
          updatedAt: "2026-03-29T12:05:00Z",
          updatedBy: "Vikas R",
        },
      ],
      messages: [
        {
          id: "msg_05",
          author: "Priya S",
          role: "operator",
          sentAt: "2026-03-29T10:15:00Z",
          message: "Please prioritize. Deployment starts early morning on April 4.",
        },
        {
          id: "msg_06",
          author: "Vikas R",
          role: "logistics",
          sentAt: "2026-03-29T12:05:00Z",
          message: "Accepted. QR labels will be created during the evening dispatch cycle.",
        },
      ],
      timeline: [
        {
          id: "evt_09",
          label: "Ticket opened",
          detail: "Operator requested 220 devices and 220 SD cards.",
          occurredAt: "2026-03-29T10:15:00Z",
          actor: "Priya S",
          tone: "info",
        },
        {
          id: "evt_10",
          label: "Ticket accepted",
          detail: "Logistics approved full quantity and scheduled pack-out.",
          occurredAt: "2026-03-29T12:00:00Z",
          actor: "Vikas R",
          tone: "success",
        },
      ],
      ingestionReport: null,
    },
    {
      id: "tkt_0043",
      title:
        "TVS Team B | Chennai Assembly | Deploy 2026-04-05 | Devices 180 | SD Cards 200",
      ticketType: "deployment",
      teamName: "TVS Team B",
      factoryName: "Chennai Assembly",
      deploymentDate: "2026-04-05",
      workerCount: 180,
      status: "return_shipped",
      priority: "high",
      devicesRequested: 180,
      sdCardsRequested: 200,
      requestOwner: "Anbu K",
      summary: "Return packet is in transit back to HQ after field completion.",
      nextAction: "HQ logistics must receive the return and record actual counts.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 180,
          approvedQty: 180,
          returnedQty: 180,
          receivedAtHqQty: 0,
        },
        {
          itemType: "SD cards",
          requestedQty: 200,
          approvedQty: 200,
          returnedQty: 193,
          receivedAtHqQty: 0,
        },
      ],
      packages: [
        {
          packageCode: "PKG-RET-043A",
          qrToken: "qr_043a",
          direction: "return",
          status: "return_shipped",
          itemCount: 2,
          shippedSdCardsCount: 200,
          shippedDevicesCount: 0,
          shippedUsbHubsCount: 0,
          shippedCablesCount: 0,
          receivedSdCardsCount: 193,
          receivedDevicesCount: 0,
          receivedUsbHubsCount: 0,
          receivedCablesCount: 0,
          note: "Courier handoff completed with manifest attached",
          teamName: "TVS Team B",
          factoryName: "Chennai Assembly",
          deploymentDate: "2026-04-05",
          updatedAt: "2026-04-11T18:20:00Z",
          updatedBy: "Anbu K",
        },
      ],
      messages: [
        {
          id: "msg_07",
          author: "Anbu K",
          role: "operator",
          sentAt: "2026-04-11T18:20:00Z",
          message: "Return packet shipped. Tracking number shared in manifest.",
        },
      ],
      timeline: [
        {
          id: "evt_11",
          label: "Outbound shipped",
          detail: "Dispatch closed with one mixed hardware packet and one SD pouch.",
          occurredAt: "2026-04-03T15:45:00Z",
          actor: "HQ Logistics",
          tone: "info",
        },
        {
          id: "evt_12",
          label: "Return shipped",
          detail: "Factory team shipped back the packet after deployment finished.",
          occurredAt: "2026-04-11T18:20:00Z",
          actor: "Anbu K",
          tone: "warning",
        },
      ],
      ingestionReport: null,
    },
    {
      id: "tkt_0044",
      title:
        "Transfer 2026-04-16 | Tata Team A / Pune Factory 2 -> Ashok Team C / Hosur Plant 1 | Devices 120 | SD Cards 0",
      ticketType: "transfer",
      teamName: "Ashok Team C",
      factoryName: "Hosur Plant 1",
      sourceTeamName: "Tata Team A",
      sourceFactoryName: "Pune Factory 2",
      linkedTicketId: "tkt_0041",
      deploymentDate: "2026-04-16",
      workerCount: 120,
      status: "factory_received",
      priority: "medium",
      devicesRequested: 120,
      sdCardsRequested: 0,
      requestOwner: "Raghu M",
      summary:
        "Factory-to-factory transfer completed. Devices moved from Pune Factory 2 to Hosur Plant 1.",
      nextAction:
        "Logistics should confirm if the transfer should stay open for later return tracking or close it now.",
      items: [
        {
          itemType: "Camera devices",
          requestedQty: 120,
          approvedQty: 120,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
        {
          itemType: "USB hubs",
          requestedQty: 3,
          approvedQty: 3,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
        {
          itemType: "Cables",
          requestedQty: 120,
          approvedQty: 120,
          returnedQty: 0,
          receivedAtHqQty: 0,
        },
      ],
      packages: [
        {
          packageCode: "PKG-RET-044A",
          qrToken: "qr_044a",
          direction: "return",
          status: "factory_received",
          itemCount: 1,
          shippedSdCardsCount: 0,
          shippedDevicesCount: 120,
          shippedUsbHubsCount: 3,
          shippedCablesCount: 120,
          receivedSdCardsCount: 0,
          receivedDevicesCount: 118,
          receivedUsbHubsCount: 3,
          receivedCablesCount: 119,
          note: "Inter-factory transfer pouch delivered to Hosur staging desk",
          teamName: "Ashok Team C",
          factoryName: "Hosur Plant 1",
          deploymentDate: "2026-04-16",
          updatedAt: "2026-04-16T09:40:00Z",
          updatedBy: "Vikas R",
        },
      ],
      messages: [
        {
          id: "msg_08",
          author: "Raghu M",
          role: "operator",
          sentAt: "2026-04-15T16:05:00Z",
          message:
            "Factory A can transfer 120 devices directly to Hosur instead of returning them to HQ.",
        },
        {
          id: "msg_09",
          author: "Vikas R",
          role: "logistics",
          sentAt: "2026-04-15T17:10:00Z",
          message:
            "Approved. Transfer ticket linked to the original HQ dispatch so device history stays visible.",
        },
      ],
      timeline: [
        {
          id: "evt_13",
          label: "Transfer ticket opened",
          detail: "Factory transfer requested from Pune Factory 2 to Hosur Plant 1.",
          occurredAt: "2026-04-15T16:05:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_14",
          label: "Ticket accepted",
          detail:
            "Logistics approved the factory-to-factory transfer and linked it to the original deployment ticket.",
          occurredAt: "2026-04-15T17:00:00Z",
          actor: "Vikas R",
          tone: "success",
        },
        {
          id: "evt_15",
          label: "Shipped to factory",
          detail:
            "Devices left Pune Factory 2 for Hosur Plant 1 with a QR-linked handoff packet.",
          occurredAt: "2026-04-15T20:25:00Z",
          actor: "Raghu M",
          tone: "info",
        },
        {
          id: "evt_16",
          label: "Received at factory",
          detail:
            "Hosur team received the transfer and counted a minor variance in devices and cables.",
          occurredAt: "2026-04-16T09:40:00Z",
          actor: "Priya S",
          tone: "success",
        },
      ],
      ingestionReport: null,
    },
  ],
  ingestionQueue: [
    {
      id: "ing_041",
      packageCode: "PKG-RET-041B",
      teamName: "Tata Team A",
      factoryName: "Pune Factory 2",
      deploymentDate: "2026-04-02",
      expectedSdCards: 500,
      status: "ingestion_processing",
    },
    {
      id: "ing_036",
      packageCode: "PKG-RET-036A",
      teamName: "Hindalco Team D",
      factoryName: "Nagpur Press Line",
      deploymentDate: "2026-03-31",
      expectedSdCards: 160,
      status: "transferred_to_ingestion",
    },
    {
      id: "ing_032",
      packageCode: "PKG-RET-032C",
      teamName: "Mahindra Team F",
      factoryName: "Nashik Body Shop",
      deploymentDate: "2026-03-28",
      expectedSdCards: 90,
      status: "hq_received",
    },
  ],
  inventoryItems: [
    {
      id: "inv_camera",
      itemType: "Camera devices",
      sku: "CAM-HEAD-01",
      totalUnits: 1500,
      availableUnits: 612,
      allocatedUnits: 540,
      inTransitUnits: 198,
      ingestionUnits: 0,
      missingUnits: 150,
      reorderPoint: 400,
      location: "HQ Rack A1",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T17:05:00Z",
      note: "Admin reconciled counts after return scan batch.",
      status: "critical",
    },
    {
      id: "inv_sd_cards",
      itemType: "SD cards",
      sku: "SD-256-IND",
      totalUnits: 2800,
      availableUnits: 720,
      allocatedUnits: 910,
      inTransitUnits: 610,
      ingestionUnits: 528,
      missingUnits: 32,
      reorderPoint: 850,
      location: "Vault C2",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T17:08:00Z",
      note: "Missing cards reflect latest ingestion discrepancy count.",
      status: "low_stock",
    },
    {
      id: "inv_chargers",
      itemType: "Chargers",
      sku: "CHR-65W-IND",
      totalUnits: 1700,
      availableUnits: 884,
      allocatedUnits: 520,
      inTransitUnits: 210,
      ingestionUnits: 0,
      missingUnits: 86,
      reorderPoint: 300,
      location: "HQ Rack B3",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T16:42:00Z",
      note: "Includes shortage from two incomplete factory returns.",
      status: "critical",
    },
    {
      id: "inv_reader_hubs",
      itemType: "Reader hubs",
      sku: "HUB-12X-IND",
      totalUnits: 120,
      availableUnits: 54,
      allocatedUnits: 28,
      inTransitUnits: 18,
      ingestionUnits: 12,
      missingUnits: 8,
      reorderPoint: 20,
      location: "Lab Shelf D1",
      updatedBy: "Admin Kiran",
      updatedAt: "2026-03-29T16:55:00Z",
      note: "Extra units reserved for ingestion room overflow.",
      status: "low_stock",
    },
  ],
};

export function getMockOperationsSnapshot() {
  return mockOperationsSnapshot;
}
